[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "metran"
dynamic = ["version"]
description = "Python package to perform timeseries analysis of multiple hydrological time series using a dynamic factor model."
license = { file = "LICENSE" }
readme = "README.md"
dependencies = [
    "numpy",
    "matplotlib",
    "pandas >= 2.2.2, < 3.0",
    "scipy",
    "numba",
    "pastas",
]
authors = [{ name = "W.L. Berendrecht" }]
maintainers = [
    { name = "W.L. Berendrecht", email = "wilbert@berendrechtconsultancy.nl" },
    { name = "D.A. Brakenhoff", email = "d.brakenhoff@artesia-water.nl" },
    { name = "M.A. Vonk", email = "m.vonk@artesia-water.nl" },
]
requires-python = ">= 3.11"
keywords = ["hydrology", "groundwater", "timeseries", "analysis"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Hydrology",
]

[project.urls]
homepage = "https://github.com/pastas/metran"
repository = "https://github.com/pastas/metran"
documentation = "https://metran.readthedocs.io/en/latest/"

[project.optional-dependencies]
solvers = ["lmfit >= 1.0.0"]
dino = ["hydropandas"]
linting = ["ruff"]
formatting = ["ruff"]
pytesting = [
    "metran[dino]",
    "pytest",
    "pytest-cov",
    "pytest-sugar",
    "jupyter",
    "hydropandas",
]
coveraging = ["coverage"]
rtd = ["metran[dino]", "sphinx_rtd_theme", "Ipython", "ipykernel", "jupyter", "myst_nb"]
full = ["metran[solvers]"]
dev = ["metran[solvers,linting,pytesting,coveraging]", "tox"]

[tool.setuptools.dynamic]
version = { attr = "metran.version.__version__" }

[tool.ruff]
line-length = 88
extend-include = ["*.ipynb"]
show-fixes = true
fix = false

[tool.ruff.lint]
extend-select = ["I"]
# See: https://docs.astral.sh/ruff/rules/
select = [
    "C4",  # flake8-comprehensions
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "PT",  # pytest-style
    "D",   # pydocstyle
    "B",   # flake8-bugbear
    "NPY", # numpy
]

[tool.ruff.format]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
addopts = "--strict-markers --durations=0"
markers = ["notebooks: run notebooks"]

[tool.tox]
legacy_tox_ini = """
    [tox]
    requires = tox>=4
    env_list = py311, py312, py313, py314, coverage

    [testenv]
    description = run unit tests
    extras = pytesting,full
    commands =
            pytest tests -m "not notebooks"

    [testenv:notebooks]
    description = run the notebooks
    extras = pytesting,full,dino
    commands =
            pytest tests -m "notebooks"

    [testenv:coverage]
    description = get coverage report xml
    basepython = 3.13
    extras = coveraging,pytesting,full,dino
    commands =
            coverage run -m pytest tests
            coverage xml
"""
