name: metran

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Test suite with py38-ubuntu
            python: "3.8"
            os: ubuntu-latest
            toxenv: py38
            experimental: false
          - name: Test suite with py39-ubuntu
            python: "3.9"
            os: ubuntu-latest
            toxenv: py39
            experimental: false
          - name: Test suite with py310-ubuntu
            python: "3.10"
            os: ubuntu-latest
            toxenv: py310
            experimental: false
          - name: Test suite with py311-ubuntu
            python: "3.11"
            os: ubuntu-latest
            toxenv: py311
            experimental: false
          - name: Test suite with py312-ubuntu
            python: "3.12-dev"
            os: ubuntu-latest
            toxenv: py312
            experimental: true
          - name: Formatting with black + isort
            python: "3.9"
            os: ubuntu-latest
            toxenv: format
            experimental: false
          - name: Linting with flake8
            python: "3.9"
            os: ubuntu-latest
            toxenv: lint
            experimental: false
          - name: Codacy Coverage Report
            python: "3.9"
            os: ubuntu-latest
            toxenv: coverage
            experimental: false

    name: ${{ matrix.name }}
    env:
      # Color Output
      # Rich (pip)
      FORCE_COLOR: 1
      # Tox
      PY_COLORS: 1
      # MyPy
      TERM: xterm-color
      MYPY_FORCE_COLOR: 1
      MYPY_FORCE_TERMINAL_WIDTH: 200
      # Pytest
      PYTEST_ADDOPTS: "--color=yes"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Setup tox environment
        run: tox -e ${{ matrix.toxenv }} --notest

      - name: Test
        run: tox -e ${{ matrix.toxenv }} --skip-pkg-install

      - name: Run codacy-coverage-reporter
        if: ${{ matrix.toxenv == 'coverage' && github.repository == 'pastas/metran' && success() }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
